[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "GxKeu7VJrGhsd8SpW4RYwScbTJT9Gyh5U65afsXwSawB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
